services:
  api:
    build:
        context: ./api
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - sqlserver
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
    networks:
        - productnetwork
    restart: on-failure

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        SA_PASSWORD: "YourStrong!Passw0rd"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqlvolume:/var/opt/mssql
    networks:
        - productnetwork

networks:
  productnetwork:
    
volumes:
  sqlvolume: