services:
  api:
    build:
        context: ./API
        dockerfile: Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - sqlserver
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
    networks:
        - productnetwork
    restart: on-failure

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        SA_PASSWORD: "YourStrong!Passw0rd"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqlvolume:/var/opt/mssql
    networks:
        - productnetwork

networks:
  productnetwork:
    
volumes:
  sqlvolume: